# Generated by Django 5.1.4 on 2024-12-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zm', '0002_alter_workspace_owner_alter_workspace_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to='blocks/'),
        ),
    ]
