# Generated by Django 5.1.4 on 2024-12-26 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zm', '0003_alter_block_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={},
        ),
        migrations.RemoveField(
            model_name='block',
            name='content',
        ),
        migrations.AlterField(
            model_name='block',
            name='block_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('list', 'List')], max_length=50),
        ),
        migrations.CreateModel(
            name='ImageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blocks/')),
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_block', to='zm.block')),
            ],
        ),
        migrations.CreateModel(
            name='ListBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.TextField()),
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='list_block', to='zm.block')),
            ],
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text_block', to='zm.block')),
            ],
        ),
    ]
