# Generated by Django 5.1.4 on 2025-01-04 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zm', '0004_alter_block_options_remove_block_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('list', 'List'), ('calendar', 'Calendar')], max_length=50),
        ),
        migrations.CreateModel(
            name='CalendarBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.TextField()),
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_block', to='zm.block')),
            ],
        ),
    ]
