# Generated by Django 5.1.4 on 2025-01-06 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zm', '0005_alter_block_block_type_calendarblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('list', 'List'), ('calendar', 'Calendar'), ('toggle', 'Toggle'), ('todo', 'ToDo')], max_length=50),
        ),
        migrations.CreateModel(
            name='ToDoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(default='[]')),
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='todo_block', to='zm.block')),
            ],
        ),
        migrations.CreateModel(
            name='ToggleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collapsed', models.BooleanField(default=False)),
                ('items', models.TextField(default='')),
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='toggle_block', to='zm.block')),
            ],
        ),
    ]
