# Generated by Django 5.1.4 on 2025-01-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zm', '0006_alter_block_block_type_todoblock_toggleblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toggleblock',
            name='items',
        ),
        migrations.AddField(
            model_name='todoblock',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='toggleblock',
            name='data',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='toggleblock',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
