# Generated by Django 5.1.4 on 2025-02-25 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zm', '0007_remove_toggleblock_items_todoblock_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='zm.block'),
        ),
    ]
