# Generated by Django 5.1.4 on 2025-03-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zm', '0008_block_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoblock',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='toggleblock',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
